name: CI/CD Pipeline with BugBug

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  run-bugbug-tests:
    runs-on: ubuntu-latest
    name: Run BugBug Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run BugBug Cloud Runner
        id: run-bugbug-tests
        uses: bugbug-io/bugbug-github-action@v1.2.1
        with:
          apiToken: ${{ secrets.BUGBUG_API_TOKEN }}
          testId: 08fb6a17-6aaf-4e87-b09e-dfcdf2f72c4b

      - name: Getting Run Output
        run: |
          echo "Suite Run ID: ${{ steps.run-bugbug-tests.outputs.suiteRunId }}"
          echo "Test Run ID: ${{ steps.run-bugbug-tests.outputs.testRunId }}"

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bugbug-test-report
          path: report.xml